Repository ithaka/aiw-ui, pull requests merged in 2019-12, with the labels that each got.

#1190 PLATO-384: removed ethnio survey
  src/app/_services/script.store.ts
  src/app/asset-page/asset-page.component.ts
  src/app/image-group-page/image-group-page.component.ts
  src/app/search-page/search-page.component.ts
Labels: Ready For Review

#1191 SRCHX-138: Allow only one date filter on advanced search
  src/app/_services/asset-search.service.ts
  src/app/_services/assets.service.ts
  src/app/asset-filters/asset-filters.component.ts
  src/app/modals/search-modal/search-modal.component.ts
  src/app/modals/search-modal/search-query.ts
Labels: Ready For Review

#1201 PLATO-223: Image Groups Modals Have Keyboard Trap
  src/app/asset-page/agree-modal/agree-modal.component.pug
  src/app/asset-page/agree-modal/agree-modal.component.ts
  src/app/image-group-page/terms-and-conditions/terms-and-conditions.component.pug
  src/app/image-group-page/terms-and-conditions/terms-and-conditions.component.ts
  src/app/modals/generate-citation/generate-citation.component.pug
  src/app/modals/generate-citation/generate-citation.component.ts
  src/app/modals/new-ig-modal/new-ig-modal.component.pug
  src/app/modals/share-ig-link/share-ig-link.component.pug
  src/app/modals/share-ig-link/share-ig-link.component.ts
  src/app/modals/share-link-modal/share-link-modal.component.pug
  src/app/modals/share-link-modal/share-link-modal.component.ts
Labels: Accessibility, Ready For Review

#1203 PLATO-219 & 226: add aria labels to ImageViewer buttons.
  src/app/asset-page/artstor-viewer/artstor-viewer.component.html
Labels: Accessibility
