Repository ithaka/aiw-ui, pull requests merged in 2019-06, with the labels that each got.

#1034 Air 2306
  src/app/login-form/login-form.component.ts
  src/app/pact/user-register.pact.spec.ts
  src/app/pact/user-update.pact.spec.ts
  src/app/register/register.component.ts
  src/app/shared/auth.service.ts
  src/karma.conf.js
Labels: PACT, Ready For Review

#1040 Air 1735
  src/app/_services/thumbnail.service.ts
  src/app/asset-grid/asset-grid.component.ts
  src/app/asset-grid/thumbnail/thumbnail.component.ts
  src/app/asset-grid/thumbnail/thumbnail.spec.ts
  src/app/asset-page/artstor-viewer/artstor-viewer.component.scss
  src/app/asset-page/asset-page.component.pug
  src/app/asset-page/asset-page.component.scss
  src/app/asset-page/asset-page.component.ts
  src/app/browse-page/tag/tag.component.pug
  src/app/browse-page/tag/tag.component.ts
  src/app/image-group-pp-page/image-group-pp-page.component.pug
  src/app/image-group-pp-page/image-group-pp-page.component.ts
  src/app/modals/add-to-group/add-to-group.component.pug
  src/app/modals/add-to-group/add-to-group.component.ts
  src/app/modals/share-link-modal/share-link-modal.component.pug
  src/app/modals/share-link-modal/share-link-modal.component.ts
  src/app/pact/group-api.pact.spec.ts
  src/app/pact/metadata-api.pact.spec.ts
  src/app/pact/user-register.pact.spec.ts
  src/app/pact/user-update.pact.spec.ts
  src/app/shared/assets.spec.ts
  src/app/shared/group-title/group-title.component.pug
  src/assets/i18n/en.json
  src/assets/img/icon-arrow-back.svg
  src/assets/styleguide/styles/all.css
  src/sass/core/_variables.scss
  src/sass/modules/_icons.scss
Labels: Ready For Review

#1037 AIR-2304
  src/app/asset-page/artstor-viewer/artstor-viewer.component.ts
Labels: Ready For Review

#1043 AIR-2331
  server/server.ts
  src/app/app.routes.ts
  src/app/home/home.component.ts
Labels: Ready For Review

#1053 AIR-2034
  src/app/home/featured/featured.component.pug
Labels: Ready For Review

#1055 Air 2282: User access Pacts
  src/app/_services/auth.service.ts
  src/app/login-form/login-form.component.ts
  src/app/pact/user-access.pact.spec.ts
  src/app/pact/user-register.pact.spec.ts
  src/karma.conf.js
Labels: Approved. Merge On Hold, PACT

#1059 AIR-2415
  src/app/_services/flag.service.ts
  src/app/_services/image-group.service.ts
  src/app/app.component.ts
  src/app/image-group-page/image-group-page.component.ts
Labels: Ready For Review
