Repository ithaka/aiw-ui, pull requests merged in 2019-05, with the labels that each got.

#994 AIR-2309(remove prepending of viewer2)
  src/app/category-page/category-page.component.pug
Labels: Ready For Review

#995 Edit Personal Collection image preview fix
  src/app/modals/edit-personal-collection/edit-personal-collection.component.scss
Labels: CSS Fix, Ready For Review

#997 AIR-1973
  src/app/asset-page/asset-page.component.ts
Labels: Includes Ruby Test, Ready For Review

#1004 2336-survey for groups
  src/app/app.component.ts
  src/app/shared/script.store.ts
Labels: Ready For Review

#1021 AIR-2270
  src/app/asset-page/asset-page.component.pug
  src/app/asset-page/asset-page.component.scss
  src/app/asset-page/asset-page.component.ts
  src/app/asset-page/licenses.ts
Labels: work in progress
