Repository ithaka/aiw-ui, pull requests merged in 2019-07, with the labels that each got.

#1086 Air 2439
  server/server.ts
  src/app/_services/auth.service.ts
  src/app/asset-page/asset-page.component.ts
Labels: Ready For Review, enhancement

#1080 Air 2307
  config/pact.publish.js
  src/app/_services/account.service.ts
  src/app/_services/auth.service.ts
  src/app/pact/_auth-providers.ts
  src/app/pact/metadata-api.pact.spec.ts
  src/app/pact/user-access.pact.spec.ts
  src/app/pact/user-register.pact.spec.ts
  src/app/pact/user-update.pact.spec.ts
  src/karma.conf.js
Labels: PACT, Ready For Review

#1096 AIR-2416
  src/app/_services/image-group.service.ts
  src/app/image-group-page/image-group-page.component.ts
  src/sass/modules/_buttons.scss
Labels: Ready For Review

#1101 AIR-2238
  package.json
  src/app/app.component.ts
  src/app/asset-page/artstor-viewer/artstor-viewer.component.scss
  src/app/asset-page/asset-page.component.pug
  src/app/asset-page/asset-page.component.scss
  src/polyfills.ts
  src/sass/modules/_viewer.scss
  yarn.lock
Labels: Ready For Review, Yarn Add..., low-priority

#1104 AIR-2458
  src/app/asset-page/asset-page.component.pug
  src/app/asset-page/asset-page.component.ts
  src/app/shared/datatypes/asset.interface.ts
Labels: Ready For Review
