Repository ithaka/aiw-ui, pull requests merged in 2020-01, with the labels that each got.

#1202 PLATO-218: Image Viewer Keyboard Instructions Availability
  src/app/asset-page/asset-page.component.pug
Labels: Accessibility, Ready For Review

#1205 SRCHX-428: Correct search results when using contributinginstitution facet
  src/app/_services/asset-search.service.ts
Labels: Ready for testing

#1208 PALS-136: Activate User Idle timeout functionality in Artstor
  src/app/_services/auth.service.ts
Labels: Ready For Review

#1214 Color accessibility fixes for AIW
  src/app/modals/generate-citation/generate-citation.component.scss
  src/app/modals/share-link-modal/share-link-modal.component.scss
  src/app/shared/group-title/group-title.component.scss
  src/app/uploader/uploader.component.pug
  src/app/uploader/uploader.component.scss
  src/sass/modules/_icons.scss
  src/sass/modules/_metadata.scss
  src/sass/modules/_modals.scss
Labels: Ready For Review

#1212 PLATO-486: Remove inactive button in artstor viewer
  src/app/asset-page/artstor-viewer/artstor-viewer.component.html
Labels: Accessibility, Ready For Review

#1215 SRCHX-230: Avoid screen readers from reading thumbnail info twice.
  src/app/asset-grid/thumbnail/thumbnail.component.pug
Labels: Accessibility, Ready for testing

#1220 PLATO-228: Toast Notifications Have Time Limits
  src/app/shared/toast/toast.component.pug
  src/app/shared/toast/toast.component.ts
Labels: Accessibility, Ready For Review

#1223 PLATO-495: Accessibility fixes for asset page
  src/app/asset-page/asset-page.component.pug
  src/app/asset-page/asset-page.component.scss
  src/app/asset-pp-page/asset-pp-page.component.pug
Labels: Ready For Review

#1227 PALS-98: Make Login heading H1
  package.json
  src/app/login/login.component.pug
Labels: Ready For Review

#1226 SRCHX-241: Make Help button appear as underlined
  src/app/modals/search-modal/search-modal.component.pug
Labels: Ready for testing

#1228 SRCHX-240: Browse by ADL: Don't filter collections on keyup + aria-live region
  src/app/browse-page/library.component.pug
  src/app/browse-page/library.component.ts
Labels: Ready for testing

#1229 PALS-213: Don't track user idle time after log out
  src/app/_services/auth.service.ts
Labels: Ready for testing

#1230 PLATO-510: Omit Date option from Sort on Personal Collection page
  src/app/asset-grid/asset-grid.component.pug
  src/app/asset-grid/asset-grid.component.ts
Labels: Ready for testing

#1231 SRCHX-242: Add visually hidden label on Search input
  src/app/shared/search/search.component.pug
Labels: Ready for testing

#1233 PLATO-240: Added aria alerting for the error region
  src/app/uploader/uploader.component.pug
Labels: Ready For Review

#1232 SRCHX-429: Show outline on showdow for pagination controls
  src/app/shared/pagination/pagination.component.scss
Labels: Accessibility, Ready for testing

#1238 SRCHX-243-283: Accessibility updates for AIW
  src/app/shared/nav/nav.component.pug
  src/app/shared/search/search.component.pug
Labels: Accessibility, Ready for testing

#1239 PLATO-496: Automated accessibility fixes for image group page
  src/app/asset-grid/asset-grid.component.pug
  src/app/asset-grid/asset-grid.component.ts
  src/app/asset-grid/thumbnail/thumbnail.component.pug
  src/app/modals/add-to-group/add-to-group.component.pug
  src/app/shared/pagination/pagination.component.pug
Labels: Accessibility, Ready for testing

#1240 PLATO-206: Clean up help link/icon css rules and enhance for better accessibility
  src/app/modals/add-to-group/add-to-group.component.pug
  src/app/modals/add-to-group/add-to-group.component.scss
  src/app/modals/add-to-group/add-to-group.component.ts
  src/app/modals/new-ig-modal/new-ig-modal.component.pug
  src/app/modals/share-ig-link/share-ig-link.component.pug
  src/app/modals/share-link-modal/share-link-modal.component.pug
  src/app/modals/share-link-modal/share-link-modal.component.ts
  src/app/uploader/uploader.component.pug
  src/app/uploader/uploader.component.scss
  src/sass/app.scss
  src/sass/modules/_modals.scss
Labels: Ready for testing

#1241 PLATO-496: Adding missing pagination variable
  src/app/shared/pagination/pagination.component.ts
Labels: Ready For Review

#1242 PLATO-496: Reformatting badge icons in AIW asset group thumbnails
  src/app/asset-grid/thumbnail/thumbnail.component.pug
Labels: Ready For Review
