Repository ithaka/aiw-ui, pull requests merged in 2020-03, with the labels that each got.

#1254 SRCHX-447-448: Better accessiblity fixes for browse and home page
  src/app/browse-page/library.component.pug
  src/app/home/featured/featured.component.pug
Labels: Accessibility, Ready for testing

#1258 SRCHX-549: Sort collection results by `worksequence_num` on collection page
  src/app/_services/asset-search.service.ts
Labels: Production Bug, Ready for testing

#1256 PLATO-569: Hover state accessibility fixes
  .nvmrc
  package.json
  src/app/asset-page/asset-page.component.pug
  src/app/asset-page/asset-page.component.scss
  yarn.lock
Labels: Accessibility, Ready for testing, dependencies

#1261 SRCHX-553: Sort by worksequence in Duplicates and Details
  src/app/_services/asset-search.service.ts
Labels: Ready for testing

#1263 PALS-318: Update slideshow on AIW homepage
  src/assets/i18n/en.json
  src/assets/img/featured-collections/Carnegie_Carters.jpg
  src/assets/img/featured-collections/Carnegie_Eakins.jpg
  src/assets/img/featured-collections/Lessing_Valloton.jpg
Labels: Ready for testing

#1266 BLUE-206: Update footer columns spacing for smaller viewports
  src/app/shared/footer/footer.component.pug
Labels: Accessibility

#1267 BLUE-206: Divide out bottom sections
  src/app/shared/footer/footer.component.pug
Labels: Accessibility
