Repository ithaka/aiw-ui, pull requests merged in 2020-02, with the labels that each got.

#1244 PLATO-540: Log artstor_print_image in C5
  src/app/asset-page/asset-page.component.pug
  src/app/asset-page/asset-page.component.ts
Labels: Ready for testing

#1248 PLATO-550: Add link to IIIF viewer keyboard instructions
  src/app/asset-page/artstor-viewer/artstor-viewer.component.html
Labels: Accessibility, Ready for testing

#1250 PALS-276: Add Brand survey on Artstor
  src/app/_services/script.store.ts
  src/app/app.component.ts
Labels: Ready for testing

#1249 SRCHX-511: Make sure that the request id is logged properly for the artstor_search event
  src/app/_services/assets.service.ts
  src/app/search-page/search-page.component.ts
Labels: Production Bug, Ready for testing

#1251 SRCHX-2444-248-496: Multiple AIW Accessibility fixes
  src/app/asset-page/asset-page.component.pug
  src/app/modals/login-req-modal/login-req-modal.component.pug
  src/app/modals/login-req-modal/login-req-modal.component.ts
  src/app/modals/search-modal/search-modal.component.pug
  src/app/search-page/search-page.component.pug
  src/assets/i18n/en.json
Labels: Accessibility, Ready for testing

#1252 SRCHX-137: Allow skipping of large sections in Advanced Search
  src/app/modals/search-modal/search-modal.component.pug
  src/app/modals/search-modal/search-modal.component.scss
  src/app/modals/search-modal/search-modal.component.ts
Labels: Accessibility, Ready for testing

#1253 SRCHX-447-448-247:
  src/app/asset-page/asset-page.component.ts
  src/app/browse-page/browse-page.component.pug
  src/app/browse-page/browse-page.component.scss
  src/app/browse-page/library.component.pug
  src/app/browse-page/library.component.ts
  src/app/home/featured/featured.component.pug
  src/app/home/featured/featured.component.scss
  src/app/home/featured/featured.component.ts
  src/app/home/home.component.pug
  src/app/home/home.component.scss
Labels: Accessibility, Ready for testing
