Repository ithaka/aiw-ui, pull requests merged in 2020-04, with the labels that each got.

#1268 PLATO-609: Success and error messaging accessibility
  src/app/account-page/account-page.component.pug
  src/app/asset-page/asset-page.component.pug
  src/app/modals/change-password/change-password.component.pug
  src/app/modals/edit-personal-collection/edit-personal-collection.component.pug
  src/app/modals/generate-citation/generate-citation.component.pug
  src/app/modals/share-ig-link/share-ig-link.component.pug
  src/app/register/register.component.pug
  src/assets/styleguide/styles/all.css
  src/sass/modules/_forms.scss
Labels: Accessibility, Ready for testing

#1269 PLATO-605: Allows buttons to grow in height when needed
  src/sass/modules/_buttons.scss
Labels: Ready For Review

#1270 PLATO-609-2: Moving live regions down onto the feedback elements
  src/app/account-page/account-page.component.pug
  src/app/asset-page/asset-page.component.pug
  src/app/modals/change-password/change-password.component.pug
  src/app/modals/edit-personal-collection/edit-personal-collection.component.pug
  src/app/register/register.component.pug
Labels: Accessibility, Ready For Review

#1273 BLUE-205: Make links and filters accessible on mobile
  src/app/category-page/category-page.component.pug
  src/app/category-page/category-page.component.scss
  src/app/category-page/category-page.component.ts
  src/app/collection-page/collection-page.component.pug
  src/app/collection-page/collection-page.component.scss
  src/app/collection-page/collection-page.component.ts
  src/app/modals/search-modal/search-modal.component.scss
  src/app/nav-menu/nav-menu.component.pug
  src/app/search-page/search-page.component.pug
  src/app/search-page/search-page.component.scss
  src/app/search-page/search-page.component.ts
  src/app/shared/search/search.component.scss
Labels: Accessibility

#1272 BLUE-210: Update tooltips to be WCAG compliant with Pharos tooltips
  package.json
  src/app/app.module.ts
  src/app/asset-grid/asset-grid.component.pug
  src/app/asset-grid/thumbnail/thumbnail.component.pug
  src/app/asset-page/artstor-viewer/artstor-viewer.component.html
  src/app/asset-page/artstor-viewer/artstor-viewer.component.scss
  src/app/asset-page/asset-page.component.pug
  src/app/browse-page/browse-groups/general-search.component.pug
  src/app/collection-badge/collection-badge.component.pug
  src/app/modals/add-to-group/add-to-group.component.pug
  src/app/modals/loading-state/loading-state.component.pug
  src/app/nav-menu/nav-menu.component.scss
  src/app/shared/nav/nav.component.pug
  src/assets/icon/android-icon-192x192.png
  src/assets/icon/android-icon-96x96.png
  src/assets/icon/apple-icon-114x114.png
  src/assets/icon/apple-icon-144x144.png
  src/assets/icon/apple-icon-152x152.png
  src/assets/icon/apple-icon-57x57.png
  src/assets/icon/apple-icon-60x60.png
  src/assets/icon/apple-icon-72x72.png
  src/assets/icon/apple-icon-76x76.png
  src/assets/icon/apple-icon-precomposed.png
  src/assets/icon/apple-icon.png
  src/assets/icon/browserconfig.xml
  src/assets/icon/favicon-160x160.png
  src/assets/icon/favicon-16x16.png
  src/assets/icon/favicon-196x196.png
  src/assets/icon/favicon-32x32.png
  src/assets/icon/favicon-96x96.png
  src/assets/icon/favicon.ico
  src/assets/icon/ms-icon-144x144.png
  src/assets/icon/ms-icon-150x150.png
  src/assets/icon/ms-icon-310x150.png
  src/assets/icon/ms-icon-310x310.png
  src/assets/icon/ms-icon-70x70.png
  src/polyfills.ts
  src/sass/modules/_cards.scss
  yarn.lock
Labels: Accessibility, Ready for testing

#1275 BLUE-210: Add es5 adapter polyfill
  package.json
  src/polyfills.ts
  yarn.lock
Labels: Ready for testing

#1278 SRCHX-573: Wrap text for group-browse Titles for smaller screens
  src/app/browse-page/card-view/card-view.component.pug
  src/app/browse-page/card-view/card-view.component.scss
Labels: Accessibility, CSS Fix, Ready for testing

#1280 SRCHX-574-576: Add alert role to error messages for screen readers
  src/app/asset-grid/asset-grid.component.pug
  src/app/modals/search-modal/search-modal.component.pug
Labels: Accessibility, Ready for testing

#1282 BLUE-260: Support web components in IE11
  angular.json
  babel.config.js
  browserslist
  custom-webpack.config.js
  package.json
  src/app/app.module.ts
  src/app/shared/datatypes/collection-type-handler.ts
  src/main.ts
  src/polyfills.ts
  yarn.lock
Labels: Production Bug, Ready for testing, Yarn Install, dependencies

#1281 SRCHX-577: Adjust styling on date filter when zoomed in
  src/app/asset-filters/asset-filters.component.scss
Labels: Accessibility, CSS Fix, Ready for testing

#1284 BLUE-254: Remove breaks from tooltip content
  src/app/asset-grid/thumbnail/thumbnail.component.pug
  src/app/asset-page/artstor-viewer/artstor-viewer.component.html
Labels: status/ready for testing
