Repository ithaka/aiw-ui, pull requests merged in 2021-04, with the labels that each got.

#1318 SRCHX-1166: OneTrust Cookie Compliance
  src/app/_services/flag.service.ts
  src/app/app.component.ts
  src/app/app.service.ts
  src/app/shared/footer/footer.component.ts
  src/index.html
Labels: status/ready for testing

#1319 SRCHX-1142: Filter selection bug fix
  src/app/asset-filters/asset-filters.component.ts
Labels: note/PROD BUG FIX, status/ready for testing

#1320 PLATO-1561: AIW accessibility fixes
  src/app/asset-page/asset-page.component.pug
  src/app/collection-badge/collection-badge.component.pug
  src/sass/modules/_viewer.scss
Labels: accessibility, status/ready for testing

#1321 SRCHX-1186: Remove AppDynamics EUM script
  src/index.html
Labels: status/ready for testing
