Repository ithaka/aiw-ui, pull requests merged in 2021-07, with the labels that each got.

#1346 Inline OneTrust script for improved EZProxy experience
  src/index.html
Labels: status/code review

#1345 SRCHX-1286: Increase timeout for search skip section links
  src/app/search-page/search-page.component.ts
Labels: note/PROD BUG FIX, status/ready for testing

#1347 SRCHX-1312: Update homepage promo image and URL for marketing
  src/assets/i18n/en.json
  src/assets/img/homepage_search_promo.jpg
  src/assets/img/promo-details.jpg
Labels: accessibility, status/ready for testing

#1348 SRCHX-1312-followup: Upload modified image for homepage ad
  src/assets/img/homepage_search_promo.jpg
Labels: status/ready for testing
